Repository canonical/identity-platform-admin-ui, pull requests merged in 2024-04, with the labels that each got.

#260 IAM 726
  .gitignore
  cmd/serve.go
  internal/config/specs.go
  internal/pool/interfaces.go
  internal/pool/pool.go
  internal/pool/pool_test.go
  internal/pool/types.go
  pkg/groups/service.go
  pkg/groups/service_test.go
  pkg/roles/service.go
  pkg/roles/service_test.go
  pkg/web/router.go
Labels: enhancement, help wanted

#267 IAM 782
  cmd/serve.go
  go.mod
  go.sum
  internal/http/types/generic.go
  internal/http/types/token.go
  internal/kratos/client.go
  pkg/identities/handlers.go
  pkg/identities/handlers_test.go
  pkg/identities/interfaces.go
  pkg/identities/service.go
  pkg/identities/service_test.go
  pkg/rules/handlers.go
  pkg/schemas/handlers.go
  pkg/schemas/handlers_test.go
  pkg/schemas/interfaces.go
  pkg/schemas/service.go
  pkg/schemas/service_test.go
  pkg/web/router.go
Labels: bug, help wanted

#273 IAM-769: add id validation to make sure it's never empty
  pkg/clients/handlers.go
  pkg/groups/handlers.go
  pkg/identities/handlers.go
  pkg/roles/handlers.go
  pkg/rules/handlers.go
Labels: bug

#278 validation/disable
  pkg/clients/handlers.go
  pkg/groups/handlers.go
  pkg/groups/handlers_test.go
  pkg/identities/handlers.go
  pkg/identities/handlers_test.go
  pkg/idp/handlers.go
  pkg/roles/handlers.go
  pkg/rules/handlers.go
  pkg/schemas/handlers.go
  pkg/schemas/handlers_test.go
  pkg/web/router.go
Labels: bug

#235 ci: release 1.6.0
  CHANGELOG.md
  internal/version/const.go
  rockcraft.yaml
Labels: autorelease: pending
